name: Health Check

on:
  schedule:
    - cron: '0-59/3 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping /health
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fso-part11.herokuapp.com/health